[project]
name = "learn-rnn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "midiutil>=1.2.1",
    "mido>=1.3.3",
    "numpy>=2.2.1",
    "setuptools>=75.8.0",
    "torch>=2.5.1",
    "tqdm>=4.67.1",
]
